name: amlworkbook
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.5
  - pandas=1.1.2
  - scikit-learn=0.23.2
  - requests=2.24.0
  - joblib=0.16.0
  - jupyter=1.0.0
  - pip
  - pip:
    - azureml-sdk==1.15.0
    - azureml-defaults==1.15.0
