name: iris_aml_steps
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.7
  - numpy=1.17.4
  - pandas=1.0.5
  - tqdm=4.47.0
  - scikit-learn=0.23.1
  - matplotlib=3.2.2
  - cudatoolkit=10.1
  - cudnn=7.6.5
  - pip=20.1.1
  - umap-learn=0.4.6
  - pip:
    # Azure
    - azureml-defaults==1.14.0
    - azureml-sdk==1.14.0
    - azure-cli==2.12.0
    - msal==1.3.0
    - msal-extensions==0.2.2
    # Development & Project dependencies
    - brotli==1.0.7
    - brotlipy==0.7.0
    - pillow==7.2.0
    - pylint==2.5.3
    - pytest==5.4.3
    - pytest-cov==2.10.0
    - pytest-mock==3.2.0
    - pytest-watch==4.2.0
    - python-dotenv==0.13.0
    - opencv-python==4.1.1.26
    - flake8==3.7.9
    - pyarrow==0.17.1
    - scikit-image==0.17.2
    - tensorflow-gpu==2.2.0
    - segmentation-models==1.0.1
    - Deepcell-Toolbox==0.6.1
    - torch===1.5.1
    - torchvision===0.6.1
    - tifffile==2020.7.4
    - hdbscan==0.8.26
    - h5py==2.10.0
    - imagecodecs==2020.5.30
    - horovod==0.19.5

